[tool.poetry]
name = "Cpp"
version = "0.1.0"
description = ""
authors = ["Uy Ha <hchanuy@gmail.com>"]

[tool.poetry.dependencies]
conan = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
