name: C/C++ CI
on:
  push:
    branches: [ master ]
jobs:
  build-and-test:
    name: macOS
    strategy:
      matrix:
        cpp_standard: [ 17, 20 ]
        cpp_compiler: [ g++-8, g++-9, clang++ ]
        os: [ macos-10.15 ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: install conan
        run: brew install conan
      - name: CMake configuration
        run: >
          cmake -B build $GITHUB_WORKSPACE
          -DCMAKE_BUILD_TYPE=RELEASE
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
      - name: Build
        run: cmake --build build --config release
      - name: Run tests
        run: ctest
        working-directory: build/tests
