name: C/C++ CI
on:
  push:
    branches: [master]
jobs:
  ubuntu:
    name: Ubuntu
    strategy:
      matrix:
        cpp_standard: [17, 20]
        compiler:
          - { cc: gcc-9, cxx: g++-9 }
          - { cc: gcc-10, cxx: g++-10 }
          - { cc: clang-10, cxx: clang++-10, version: 10 }
          - { cc: clang-11, cxx: clang++-11, version: 11 }
          - { cc: clang-12, cxx: clang++-12, version: 12 }
        os: [ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Install conan
        run: python3 -m pip install conan
      - name: Install clang dependencies
        run: sudo apt install libc++-${{matrix.compiler.version}}-dev libc++abi-${{matrix.compiler.version}}-dev libunwind-dev
        if: startsWith(matrix.compiler.cc, 'clang')
      - name: CMake configuration
        run: >
          cmake --preset debug
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}
          -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
      - name: Build
        run: cmake --build --preset debug
      - name: Run tests
        run: ctest
        working-directory: cmake-build-debug/tests
